team8finalproject/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace team8finalproject.Models
{

    public enum StockType
    {
        [Display(Name = "Ordinary Stock")] Ordinary,
        [Display(Name = "Index Fund")] IndexFund,
        [Display(Name = "Exchange Transfer Funds")] ETF,
        [Display(Name = "Mutual Fund")] MutualFund,
        [Display(Name = "Future Shares")] Future
    }

    public class Stock
    {
       
        public Int32 StockID { get; set; }

        [Required(ErrorMessage = "Ticker Symbol is required.")]
        [Display(Name = "Ticker Symbol")]
        public string Ticker { get; set; }

        [Required(ErrorMessage = "Stock Type is required.")]
        [Display(Name = "Stock Type")]
        public StockType StockType { get; set; }

        [Required(ErrorMessage = "Stock Name is required")]
        [Display(Name = "Stock Name")]
        public string StockName { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        [Required(ErrorMessage = "Price is required.")]
        [Display(Name = "Stock Price")]
        public Decimal Price { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        [Required(ErrorMessage = "Fee is required.")]
        [Display(Name = "Stock Fee")]
        public Decimal Fee { get; set; }
        public List<PortfolioDetail> PortfolioDetail { get; set; }
        public Stock()
        {
            if (PortfolioDetail == null)
            {
                PortfolioDetail = new List<PortfolioDetail>();
            }
        }
    }
}

team8finalproject/Controllers/PortfolioDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using team8finalproject.DAL;
using team8finalproject.Models;

namespace team8finalproject.Controllers
{
    public class PortfolioDetailController : Controller
    {
        private readonly AppDbContext _context;

        public PortfolioDetailController(AppDbContext context)
        {
            _context = context;
        }

        //GET: PortfolioDetail
        public IActionResult Index(Int32 stockID)
        {
            List<PortfolioDetail> Pdt = _context.PortfolioDetails
                .Include(Pd => Pd.Stock)
                .Include(pd => pd.Product.Customer)
                .Where(P => P.Product.ProductID == stockID).ToList();
            return View(Pdt);

        }
        /*
        //GET: PortfolioDetail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioDetail = await _context.PortfolioDetails
                .FirstOrDefaultAsync(m => m.PortfolioDetailID == id);
            if (portfolioDetail == null)
            {
                return NotFound();
            }

            foreach (var s in _context.Stocks)
            {
                s.Price = s.Price;
            }
            foreach (var p in _context.Transactions)
            {
                p. = p.Stock.CurrentPrice * p.NumberOfShares;
            }
            if (stockPortfolio.StockPurchases.Count != 0)
            {
                stockPortfolio.StockPortionValue = 0;
                foreach (var v in stockPortfolio.StockPurchases)
                {
                    stockPortfolio.StockPortionValue += v.TotalStockValue;
                    v.ChangeInPrice = v.Stock.CurrentPrice - v.InitialSharePrice;
                    v.TotalChange = v.TotalStockValue - (v.NumberOfShares * v.InitialSharePrice);
                    v.StockPurchaseDisplay = v.Stock.StockName + ", Current Price: " + v.Stock.CurrentPrice.ToString("c") + ", Number of shares: " + v.NumberOfShares;
                }
            }
            db.SaveChanges();

            return View(portfolioDetail);
        }
*/

        //GET: PortfolioDetail/Purchase/5
        public IActionResult Purchase(Int32 stockID)
        {
            // finds the user's portfolio
            PortfolioDetail Pdt = new PortfolioDetail();
            var product = _context.Products.Where(p => p.Customer.UserName == User.Identity.Name)
                .Where(p => p.ProductType == ProductTypes.Portfolio).ToList();
            if (product.Count != 0)
            {
                Pdt.Product = product[0];
                // finds the stock
                Pdt.Stock = _context.Stocks.Find(stockID);
                Pdt.StockPrice = Pdt.Stock.Price;
                return View(Pdt);
            }
            // user doesn't have a stock portfolio
            return RedirectToAction("CreatePortfolio", "Product");
        }

        //POST: PortfolioDetail/Purchase
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Purchase([Bind("PortfolioDetailID,NumShares,StockPrice,ExtendedPrice,Stock,Product")] PortfolioDetail portfolioDetail, int stockID)
        {
            // finds the portfolio
            var product = _context.Products.Where(p => p.Customer.UserName == User.Identity.Name)
                .Where(p => p.ProductType == ProductTypes.Portfolio).ToList();

            if (product.Count != 0)
            {
                portfolioDetail.Product = product[0];
                // set stock price
                Stock stock = _context.Stocks.Find(stockID);
                portfolioDetail.Stock = stock;
                portfolioDetail.StockPrice = portfolioDetail.Stock.Price;
                // set extended price
                portfolioDetail.ExtendedPrice = portfolioDetail.StockPrice * portfolioDetail.NumShares;

            }
            // product not found
            else
            {
                return View(portfolioDetail);
            }
            // fee
            Transaction fee = new Transaction();
            fee.Amount = (-portfolioDetail.Stock.Fee);
            fee.Description = "Fee: " + portfolioDetail.Stock.StockName;
            fee.Date = DateTime.Today;
            fee.Number = (int)Utilities.GenerateTransactionNumber.GetNextTransactionNumber(_context);
            fee.TransactionType = TransactionTypes.Fee;
            fee.Product = portfolioDetail.Product;
            portfolioDetail.Product.Fees = portfolioDetail.Product.Fees + portfolioDetail.Stock.Fee;
            _context.Transactions.Add(fee);

            portfolioDetail.Product.AccountBalance += fee.Amount;

            // update Stock Value
            portfolioDetail.Product.StockValue += portfolioDetail.ExtendedPrice;

            if (ModelState.IsValid)
            {
                _context.Add(portfolioDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Product", new { id = portfolioDetail.Product.ProductID });
            }
            ViewBag.AllStocks = GetAllStocks();
            return View(portfolioDetail);
        }

        //GET: PortfolioDetail/Sell/5
        public IActionResult Sell(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            PortfolioDetail portfolioDetail = _context.PortfolioDetails
                .Include(p => p.Stock)
                .Include(p => p.Product)
                .FirstOrDefault(p => p.Product.ProductID == id);
            
            if (portfolioDetail == null)
            {
                return NotFound();
            }
            return View(portfolioDetail);
        }

        //POST: PortfolioDetail/Sell/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Sell(int id, [Bind("PortfolioDetailID,NumShares,StockPrice,ExtendedPrice")] PortfolioDetail portfolioDetail)
        {
            PortfolioDetail dbPD = _context.PortfolioDetails
                .Include(p => p.Stock)
                .Include(p => p.Product)
                .FirstOrDefault(p => p.Product.ProductID == id);

            // update num of shares
            dbPD.NumShares = portfolioDetail.NumShares;

            // set extended price
            portfolioDetail.ExtendedPrice = portfolioDetail.StockPrice * portfolioDetail.NumShares;

            // update Stock Value
            portfolioDetail.Product.StockValue -= portfolioDetail.ExtendedPrice;

            if (id != portfolioDetail.PortfolioDetailID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(dbPD);
                _context.SaveChanges();
                RedirectToAction("Details", "Products", new { id = dbPD.Product.ProductID });
            }
            return View(dbPD);
        }
        /*
        //GET: PortfolioDetail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioDetail = await _context.PortfolioDetails
                .FirstOrDefaultAsync(m => m.PortfolioDetailID == id);
            if (portfolioDetail == null)
            {
                return NotFound();
            }

            return View(portfolioDetail);
        }

        //POST: PortfolioDetail/Sell/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var portfolioDetail = await _context.PortfolioDetails.FindAsync(id);
            _context.PortfolioDetails.Remove(portfolioDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        */
        private bool PortfolioDetailExists(int id)
        {
            return _context.PortfolioDetails.Any(e => e.PortfolioDetailID == id);
        }

        public SelectList GetUserProducts()
        {
            //get a list of all products from the database
            List<Product> AllProducts = _context.Products.Where(p => p.Customer.UserName == User.Identity.Name)
                .OrderBy(x => x.ProductID).ToList();


            //convert this to a select list
            //note that ProductID and ProductName are the names of fields in the Product model class
            SelectList products = new SelectList(AllProducts, "ProductID", "AccountName");

            //return the select list
            return products;

        }




         private SelectList GetAllStocks()

        {
            //get a list of all stocks from the database
            List<Stock> AllStocks = _context.Stocks.ToList();

            //convert this to a select list
            SelectList stocks = new SelectList(AllStocks, "StockID", "StockName");

            //return the select list
            return stocks;

        }

    }
}

team8finalproject/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using team8finalproject.DAL;
using team8finalproject.Models;

namespace team8finalproject.Controllers
{
    public class StockController : Controller
    {
        private readonly AppDbContext _context;

        public StockController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Stock
        public async Task<IActionResult> Index()
        {


            return View(await _context.Stocks.ToListAsync());
        }

        // GET: Stock/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .FirstOrDefaultAsync(m => m.StockID == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // GET: Stock/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stock/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles="Manager")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StockID,Ticker,StockType,StockName,Price,Fee")] Stock stock)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stock);
        }

        // GET: Stock/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

        // POST: Stock/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockID,Ticker,StockType,StockName,Price,Fee")] Stock stock)
        {
            if (id != stock.StockID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockExists(stock.StockID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stock);
        }

        // GET: Stock/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .FirstOrDefaultAsync(m => m.StockID == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stock/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stock = await _context.Stocks.FindAsync(id);
            _context.Stocks.Remove(stock);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockExists(int id)
        {
            return _context.Stocks.Any(e => e.StockID == id);
        }
    }
}

team8finalproject/Views/Stock/Create.cshtml
@model team8finalproject.Models.Stock

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Stock</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ticker" class="control-label"></label>
                <input asp-for="Ticker" class="form-control" />
                <span asp-validation-for="Ticker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockType" class="control-label"></label>
                <select asp-for="StockType" class="form-control"></select>
                <span asp-validation-for="StockType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockName" class="control-label"></label>
                <input asp-for="StockName" class="form-control" />
                <span asp-validation-for="StockName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

team8finalproject/Views/Stock/Delete.cshtml
@model team8finalproject.Models.Stock

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stock</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ticker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ticker)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StockID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

team8finalproject/Views/Stock/Details.cshtml
@model team8finalproject.Models.Stock

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Stock</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ticker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ticker)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StockID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

team8finalproject/Views/Stock/Edit.cshtml
@model team8finalproject.Models.Stock

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Stock</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StockID" />
            <div class="form-group">
                <label asp-for="Ticker" class="control-label"></label>
                <input asp-for="Ticker" class="form-control" />
                <span asp-validation-for="Ticker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockType" class="control-label"></label>
                <select asp-for="StockType" class="form-control"></select>
                <span asp-validation-for="StockType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockName" class="control-label"></label>
                <input asp-for="StockName" class="form-control" />
                <span asp-validation-for="StockName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

team8finalproject/Views/Stock/Index.cshtml
@model IEnumerable<team8finalproject.Models.Stock>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@if(User.IsInRole("Manager"))
{
    <p>
        <a asp-action="Create">Create New Stock</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ticker)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fee)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ticker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fee)
            </td>
            <td>
                @if (User.IsInRole("Customer"))
                {
                    <a asp-action="Purchase" asp-controller="PortfolioDetail" asp-route-stockID="@item.StockID">Purchase</a>
                }
                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-stockID="@item.StockID">Edit </a>
                    <a asp-action="Details" asp-route-id="@item.StockID">Details </a>
                    <a asp-action="Delete" asp-route-id="@item.StockID">Delete</a>
                }


                
            </td>
        </tr>
}
    </tbody>
</table>
    @Html.ActionLink("Stock Portfolio", "DetailsPortfolio", "Product", null, new { @class = "nav-link" })