team8finalproject/Controllers/SeedController.cs
using Microsoft.AspNetCore.Mvc;
using team8finalproject.DAL;
using System;


namespace team8finalproject.Controllers


{

   public class SeedController : Controller

    {
        private AppDbContext _db;
		private IServiceProvider serviceProvider;

        public SeedController(AppDbContext context)


        {
            _db = context;

        }

        // GET: /<controller>/


        public IActionResult Index()

        {
            return View();

        }

        public IActionResult SeedStocks()

        {
            try

            {
                Seeding.SeedStocks.SeedAllStocks(_db);

            }

            catch (NotSupportedException ex)

            {

                return View("Error", new String[] { "The stocks have already been added", ex.Message });
            }

            catch (InvalidOperationException ex)

            {

                return View("Error", new String[] { "There was an error adding stocks to the database", ex.Message });

            }

            return View("Confirm");

        }

		public IActionResult SeedPayees()

		{
			try

			{
				Seeding.SeedPayees.SeedAllPayees(_db);

			}

			catch (NotSupportedException ex)

			{

				return View("Error", new String[] { "The payees have already been added", ex.Message });
			}

			catch (InvalidOperationException ex)

			{

				return View("Error", new String[] { "There was an error adding payees to the database", ex.Message });

			}

			return View("Confirm");

		}
	}

}

team8finalproject/Views/Seed/Confirm.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Congratulations!!</h1>
<p>The data has been seeded!!</p>

<a asp-controller="Home" asp-action="Index" class="btn btn-success">Go Back to the Home Page!</a>

team8finalproject/Views/Seed/Index.cshtml
<h1>Seed Data</h1>

<p>These buttons will seed your data!  Push them to add data to your database!!</p>

<a asp-controller="Seed" asp-action="SeedPayees" class="btn btn-info">Seed Payees</a>
<a asp-controller="Seed" asp-action="SeedStocks" class="btn btn-warning">Seed Stocks</a>




<a href="~/Views/Seed/Index.cshtml">~/Views/Seed/Index.cshtml</a>